#!/bin/bash -ex

export ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export BUILD_DIR="${ROOT_DIR}/build"

export DATA_DIR="${ROOT_DIR}/data"

export SCRIPTS_DIR="${ROOT_DIR}/scripts"

export BIN_DIR="${ROOT_DIR}/bin"

export ACCTEST_WORK_DIR="${BUILD_DIR}/acceptance"

export DEV_VIRTUALENV_DIR="${BUILD_DIR}/env"

export TMP_VIRTUALENV_DIR="${BUILD_DIR}/tmpenv"

export TMP_VIRTUALENV_DIR_PY3="${BUILD_DIR}/tmpenvPy3"

export PYTHONDONTWRITEBYTECODE="no .pyc files please"

export COMMON_THEANO_FLAGS_FOR_TRAINING="floatX=float32,warn_float64=warn,optimizer=fast_run,nvcc.fastmath=True,scan.allow_gc=False,lib.cnmem=0.4"

#
# TODO(semen): pass OMP_NUM_THREADS=1 when basecalling
#
export COMMON_THEANO_FLAGS_FOR_BASECALLING="device=cpu,floatX=float32,warn_float64=warn"

export THEANO_FLAGS_FOR_ACCTEST="device=cpu,${COMMON_THEANO_FLAGS_FOR_TRAINING}"

export PATH="/usr/local/cuda/bin:${PATH}"

source ${SCRIPTS_DIR}/version-env.sh
